---
driver:
  name: vagrant
  synced_folders:
    - ["./profile_tar", "/opt", 'create: true']

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[profile_upload::default]
    attributes:
      audit:
        reporter: 'chef-compliance'
        server: <%= ENV['COMPLIANCE_API'] %>
        token: <%= ENV['COMPLIANCE_ACCESSTOKEN'] %>
        refresh_token:  <%= ENV['COMPLIANCE_REFRESHTOKEN'] %>
        insecure: true
        owner: admin
        profiles:
          - name: admin/hardening
            path: /opt/ssh-hardening.tar.gz
