---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-7.1
  - name: centos-6.7
  - name: centos-5.11
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[audit::default]
    attributes:
