---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true

platforms:
# Your vagrant box name of a windows machines you have privately sourced
- name: windows2012r2
  driver:
    # Your box or box_url should also be a privately hosted NFS, or URL,
    # to publish your private Windows boxes
    box: /vagrant/windows2012r2
    box_url: http://boxshare.yourdomain.com/vagrant/windows2012r2
  ostype: windows
  shell_type: powershell
  transport:
    name: winrm

# If you need to test a Linux-based profile, call a public box, such as this one.
- name: ubuntu-14.04
  driver:
    box: bento/ubuntu-14.04

suites:
  - name: windows
    run_list:
      # The run_list should be the wrapper cookbook.
      - recipe[wrapper_audit::default]
    attributes:
      audit:
        reporter: 'chef-automate'
        server: <%= ENV['COMPLIANCE_API'] %>
        token: <%= ENV['COMPLIANCE_ACCESSTOKEN'] %>
        refresh_token: <%= ENV['COMPLIANCE_REFRESHTOKEN'] %>
        insecure: true
        # The owner should show up in the bottom-left of the home page of Compliance.
        # If it is integrated with Chef Server, it will be the Chef Server org-name
        owner: yourchef-orgname
        profiles:
          # Example default profile already in Compliance.
          base/windows: true
          # If you create and import a custom profile you wrote, you can also add it.
          yourchef-orgname/customprofilename: true
