---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[lich_cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
